---
- name: DNS server setup
  hosts: dhcp-dns
  remote_user: guillaume

  tasks:
  - name : Install bind9 package
    apt: 
      name: 
        - bind9
        - dnsutils
      state: latest
      update_cache: yes

  - name: Configure bind9
    blockinfile:
      path: /etc/bind/named.conf.local
      block: |
        zone "lab.com" {
          type master;
          file "/etc/bind/db.lab.com";
        };
      backup: yes
    
  - name: Configure bind9 zone
    copy:
      src: conf/db.lab.com
      dest: /etc/bind/db.lab.com
      owner: root
      group: root
      mode: 0644
      backup: yes